# Generated by Django 3.2.6 on 2021-08-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='service',
            field=models.ForeignKey(help_text='Links can be added to outside resources can be added to services here. Service must already exist.', on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.TextField(help_text='Links can be added to services through the Links tab. Service must be created first.'),
        ),
    ]
