# Generated by Django 3.2.6 on 2021-08-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210825_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='view_order',
            field=models.IntegerField(default=1),
        ),
    ]
