# Generated by Django 3.2.6 on 2022-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_staff_view_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='view_order',
            field=models.IntegerField(default=1),
        ),
    ]
